### ISSUE TITLE
Extension methods in TimeStamp raise warnings when loading in Pharo 5.0

### ISSUE THREAD

**Issue by tinchodias** [estebanlm/voyage#11]
Not sure how important is this issue, but we could fix it.

`*** Warning: Warning: This package depends on the following classes:
  TimeStamp
You must resolve these dependencies before you will be able to load these definitions: 
  TimeStamp>>#bsonTypeCode
  TimeStamp>>#writeBSONOn:`

**Comment by estebanlm** [comment]
yes, we need to fix it (for Pharo5). 
With Norbert, was just to add a class called MongoTimeStamp and make him the receipt of... Mongo time stamps :P 
That has to be enough to fix it :)

**Comment by tinchodias** [comment]
Ok. 

This extension to TimeStamp belongs to Mongo-Squeak, a small package with another extension method plus the class GratuitousIncompatibilities, which holds many convenience methods. 

I think we can:

1. create a package Mongo-Pharo (or -Pharo50), and make Metacello load the proper package.
2. rename GratuitousIncompatibilities to MongoPlatform and subclass MongoSqueakPlatform and MongoPharo50Platform. This hierarchy will encapsulate the differences between platforms/versions.

For example, MongoPlatform can provide an abstract method `newTimeStampFrom:aDateAndTime`, and MongoSqueakPlatform returns TimeStamp while MongoPharo50Platform returns a MongoTimeStamp. 

Does this sound good? do you know the users of Mongo package? in fact we should discuss this in some mailing list since the code is versioned in Smaltlalkhub... Well, maybe I just implement this idea and then send a mail to discuss it.

**Comment by estebanlm** [comment]
well, I do not think so.
a TimeStamp in MongoDB is *not* a type of date time. 

For me, I would not create any Mongo-Pharo package because this is not a platform compatibility stuff. Otherwise you will need to do a Mongo-X package for placing the extensions to TimeStamp.
So… since a timestamp is not a date-time, I would: 

1) create a class MongoTimeStamp, who holds a number.
2) make the read and write there, with this number. 

We do not need any translation also because this timestamp is used *internally* in mongo, look here: https://docs.mongodb.org/manual/reference/bson-types/#timestamps

in case we need a conversion, we can add specific conversion methods to MongoTimeStamp, but I would not lose time mapping a type that is not supposed we use. 

Esteban

**Comment by tinchodias** [comment]
Ok, now I learnt more of Timestamp. Thanks! Before I just read the code and it really looks like MongoTimestamp=DateAndTime. See the marshaling methods:

	BSON>>nextTimestamp
		^self nextDateAndTime asTimeStamp

	BSON>>nextTimestampPut: aTimestamp 
		self nextDateAndTimePut: aTimestamp

However, now I see:

	nextDateAndTime
		^(GratuitousIncompatibilities intToDateAndTime: stream nextInt64)

Then, you propose to rewrite Timestamp reading to:

	BSON>>nextTimestamp
		^ MongoTimestamp fromValue: stream nextInt64

similar to writing method.

**Comment by estebanlm** [comment]
yes, it was an historical error in MongoTalk :P

**Comment by tinchodias** [comment]
I commit to [http://smalltalkhub.com/#!/~MongoTalkTeam/mongotalk](sthub).

**Comment by tinchodias** [comment]
Done, but I should release a new stable version so that Voyage uses the changes. I'll wait a bit to see if somebody answers my email in pharo-users.

**Comment by tinchodias** [comment]
included in 1.9.2 of mongotalk; stable is 1.9.3.
