### ISSUE TITLE
Test Runner on VORepositoryTest hangs with MongoTalk 1.9.1 (released some days ago)

### ISSUE THREAD

**Issue by tinchodias** [estebanlm/voyage#14]
Debugging and backtracking the error, I narrowed the error to a change introduced in Mongo-Core-HolgerHansPeterFreyther.44. What I found is that the new implementation of MongoDatabase>>addCollection: no longer tolerates adding an already existing collection.

This is how adding a collection works, before and after:

- before (directly in `MongoDatabase>>addCollection:`) 

	| command reply |
	command := Dictionary new.
	command at: 'create' put: aString.
	reply := self command: command.
	reply at: 'ok' ifAbsent: [self halt].
	^MongoCollection database: self name: aString

- currently (delegated to `MongoDatabase>>addCollection:capped:size:max:`)

	| command reply |
	command := SmallDictionary new.
	command at: 'create' put: aString.
	aCapped ifTrue: [
		command at: 'capped' put: true.
		aSize ifNotNil: [command at: 'size' put: aSize].
		aMax ifNotNil: [command at: 'max' put: aMax]].
	reply := self command: command.
	(reply at: 'ok' ifAbsent: [self halt]) = 1.0 ifFalse: [
		^self error: 'Command failed'.
	].
	^MongoCollection database: self name: aString

I didn't analyse why the tests add an existing collection. So not sure if it's the test or the code that should be fixed.

But, I tried inserting the following code to tolerate adding an existing collection, and it worked fine:

	(reply at: 'ok' ifAbsent: [self halt]) = 1.0 ifFalse: [		
		"Tolerate error 48: collection already exists"
		((reply at: 'code') = 48) ifFalse: [ ^self error: 'Command failed' ]
	].

The code is not nice, but I can commit it if you agree. No idea why Travis builds don't complain on this, but I reproduced the hang on my linux in Pharo 3, 4 and 5.

Opinions?

**Comment by tinchodias** [comment]
Well, I commit a new version adding tolerance. Need to release a stable version with this change...

**Comment by noha** [comment]
Can we make that stable. I'm in a dead lock. Newest voyage is badly broken but an old version that works relies on mongo stable which includes the bogus version the throws an exception and triggers the infinite loop in voyage pool

**Comment by noha** [comment]
Ok, I did a stable release because this bug is annoying and the patch fixes it

**Comment by estebanlm** [comment]
thanks @noha :)

**Comment by Rydier** [comment]
IMHO, it should be ok to return an error when you try to add a collection that already exists; old version of error return check in addCollection incorrectly assumed the operation "succeeded" as long as an ok key was present in return, while it is the value which should determine it (as it now correctly does).

At least to me, it seems a bit strange that a selectAll: on a fresh Resolver would result in addCollection: being called... Rather than telling db to create a collection whenever it can't be found in local cache, shouldn't it at least try populating/refreshing the cache first?

This is especially annoying with the fixed addCollection: since the enclosing Error handler in Voyage is also buggy and deadlocks the image rather than end with a debugger being raised.

**Comment by noha** [comment]
I uploaded a proposal how to solve this. I introduced MongoCollectionAlreadyExists error. It is thrown when the collection that should be created already exists. There is a new method getCollection: that just ignores the error and returns the collection. So Voyage should use getCollection: in the resolver to retrieve the collection. In mongo the collection is created anyway whenever accessed first. So that should be as close to mongo as possible

**Comment by LucFabresse** [comment]
How can I load the stable version of Voyage that integrates this fix?

I've checked a lot of different repos: 
- github/estebanlm/voyage 
- sthub/estebanlm/Voyage 
- sthub/Pharo/MetaRepoPharo4
- sthub/Pharo/MetaRepoPharo5
and they all have an old ConfigOfVoyage

**Comment by tinchodias** [comment]
@LucFabresse the master branch of github/estebanlm/voyage is ok, but it loads the stable version of ConfiguationOfMongoTalk where there isn't a release with this change yet. We can release 1.9.4 with it

**Comment by tinchodias** [comment]
Well, since there was no more discussion in 8 days, I decided to release 1.9.4. So, now, this change should be loaded with the master branch of github/estebanlm/voyage. @LucFabresse

**Comment by LucFabresse** [comment]
Hi Guys,

Thanks for your replies but I still do not know how to load the right
version.
Do you have a snippet?
If I do:

Metacello new
    repository: 'github://estebanlm/voyage/mc';
    baseline: 'VoyageMongo';
    load.

Voyage Tests hang the image
and
MongoTest >> testCollections is yellow

(yes I have a local running MongoDb and Mongo local works)

Thanks,

#Luc

2016-03-29 15:01 GMT+02:00 Esteban Lorenzano <notifications@github.com>:

**Comment by tinchodias** [comment]
Maybe you shouldn't load master but a tagged stable version. 

There is https://github.com/estebanlm/voyage/tree/v1.1.0, but I guess we have to create a new stable version including a fix to the BaselineOfVoyage that @noha recently did.

**Comment by tinchodias** [comment]
BTW, I confirm `testCollections` is yellow, as well as `testGetNoneExistingCollection`.

Didn't check the cause of these test failures. May be Norbert's change? Voyage's travis isn't configured to run Mongo tests so I didn't notice it.

**Comment by noha** [comment]
I loaded master in a fresh pharo5 image and all tests are green. Well, after I fixed the mongo tests :)

**Comment by tinchodias** [comment]
@noha Great! so what's best for Luc? should he use the master branch?

**Comment by LucFabresse** [comment]
Thanks Martin to check that ;-)

#Luc

2016-04-01 5:32 GMT+02:00 Martín Dias <notifications@github.com>:
