### ISSUE TITLE
OID does not create correct ids

### ISSUE THREAD

**Issue by estebanlm** [estebanlm/voyage#6]
(reported by Sabine)

on mongo console, this brings me a persons information from mongo db 
db.Persons.find({"_id" : ObjectId("75b900000000000000000000")}) 

I try to query the same person from pharo and I do not succeed. 

This makes my image hanging: 
RKAPerson selectMany: {('_id' -> (OID value:'75b900000000000000000000'))} 

also other variations e.g. 
RKAPerson selectMany: {('_id' -> ('75b900000000000000000000')). } asDictionary. 
                          
do not work 

Other queries like 
RKAPerson selectMany:{('lastName' -> ('Maier')).} asDictionary. 
or 
RKAPerson selectMany:{('nextTripNumber' -> (57)).} asDictionary. 

work fine. 

How can I query for an object with the object id? 

check this thread: http://forum.world.st/Mongo-find-object-by-id-td4842231.html

**Comment by SabineManaa** [comment]
I made a copy and paste error, I forgot the asDictionary. But the result is the same. Both cases make hanging image.
RKAPerson selectMany: {('_id' -> (OID value:'75b900000000000000000000'))} asDictionary

**Comment by SabineManaa** [comment]
According to this thread
http://forum.world.st/voyage-mongo-randomly-wrong-OIDs-td4705396.html#a4705898

**Comment by johnnyzz** [comment]
Hi Sabine, why do you need to construct OID from String? I think this is not a bug
Consider this:
> OID value: 26555050698940995562836590593. "dec"
> OID value: 16r55CDD2B6E9A87A520F000001. "hex"

also take a look at this MongoTalk commit: http://smalltalkhub.com/#!/~MongoTalkTeam/mongotalk/versions/Mongo-BSON-HenrikSperreJohansen.43

**Comment by SabineManaa** [comment]
Hi John,

you are right. Then there is only the problem with the size of the OID remaining because your example also leads to an database entry which is not searchable by ids id.

> db.Persons.find({"_id" : ObjectId("16r55CDD2B6E9A87A520F000001")})
Fri Aug 14 14:07:12.571 Error: invalid object id: length

Can you please check the link to the MongoTalk commit, I can not find it.
Regards
Sabine

**Comment by johnnyzz** [comment]
Don't know, the link works for me...
The value is Smalltalk code, for Mongo console skip "16r" and the rest is the hex value you need.
In fact you need something like:
In Smalltalk

> 66721700641503420494781612039 printStringHex 
> 'D796E5AF5F4D5C1EF4000007'

In Mongo
> db.Persons.find({"_id" : ObjectId("D796E5AF5F4D5C1EF4000007")})

clear?

**Comment by SabineManaa** [comment]
Hi John,

yes, now it is. And it works.
Thanks a lot for your help!

Is there a reason why this is not in ConfigurationOfMongoTalk?
Regards
Sabine

**Comment by johnnyzz** [comment]
Sabine, I don't have any commit rights there, but that's good question again for mailing list :-)

**Comment by estebanlm** [comment]
Hi, 

I do not have too much to say here :)
Just one thing: changing OID write/read to force it an integer is probably not good because an ObjectID, while a number, is a special kind of number: http://docs.mongodb.org/manual/reference/object-id

About adopting packages of Henrik... how backward compatible is it?

**Comment by SabineManaa** [comment]
Hi Esteban,

it is both a LargePositiveInteger, in original codes case:

value := LargePositiveInteger new: 12.
value := (value bitOr: DateAndTime now asSeconds) bitShift: 24.
value := (value bitOr: self class machineIdentifier) bitShift: 16.
value := (value bitOr: ((Processor activeProcess hash bitShift: -16)
bitAnd: 16rFFFF)) bitShift: 24.
value := (value bitOr: self class counterNext)

and in Henriks code like this:

| processIdentifier |
processIdentifier := Processor activeProcess basicIdentityHash.
value := LargePositiveInteger new: 12.
value
replaceFrom: 9 to: 12 with: Time totalSeconds - 2177452800 startingAt: 1;
replaceFrom: 6 to: 8 with: self class machineIdentifier startingAt: 1;
digitAt: 5 put: (processIdentifier bitAnd: 16rFF);
digitAt: 4 put: ((processIdentifier bitShift: -8) bitAnd: 16rFF);
replaceFrom: 1 to: 3 with: self class counterNext startingAt: 1

So I don't exactly understand what you mean by saying "force it an integer".
Henriks code uses unixtime instead of squeak time, other counter etc and
seems to be faster, see the comment in the commit. It seems to be backward
compatible but here also I don't exactly know what you intend.

I assume, that it will come into the next stable version of MONGO-BSON
package?
Till then I have it in my own configurationOf.

Regards
Sabine


2015-08-17 11:26 GMT+02:00 Esteban Lorenzano <notifications@github.com>:

**Comment by estebanlm** [comment]
I meant inside MongoDB. There it is not an integer… it is a special type.
You can create an OID with no matter what number inside (as long as is not bigger than 12b)
But I think in the driver it needs to be treated as something different than a number.  

Esteban

**Comment by SabineManaa** [comment]
Hi Esteban,

I dont understand why you are telling this to me because I don't want to
manipulate something inside mongo, I only wanted to use the implementation
of Henrik now instead of the old one.

Are you sure about the number inside (not larger than 12)? I have OIDs
which are to small:

> db.Trips.find({"person.__id" : ObjectId("2E7A4")})

Mon Aug 17 14:20:56.990 Error: invalid object id: length

> db.Trips.find({"person.__id" : ObjectId("190372")})

Mon Aug 17 14:21:10.815 Error: invalid object id: length


I think they have to be exactly 12.


Will the implementation of Henrik will come into the next stable version of
MONGO-BSON package?


Regards

Sabine




2015-08-17 14:04 GMT+02:00 Esteban Lorenzano <notifications@github.com>:

> I meant inside MongoDB. There it is not an integer… it is a special type.
> You can create an OID with no matter what number inside (as long as is not
> bigger than 12b)
> But I think in the driver it needs to be treated as something different
> than a number.
>
> Esteban
>
>

**Comment by estebanlm** [comment]
> On 17 Aug 2015, at 14:24, SabineManaa <notifications@github.com> wrote:
> 
> Hi Esteban,
> 
> I dont understand why you are telling this to me because I don't want to
> manipulate something inside mongo, I only wanted to use the implementation
> of Henrik now instead of the old one.
> 
> Are you sure about the number inside (not larger than 12)? I have OIDs
> which are to small:
> 
> > db.Trips.find({"person.__id" : ObjectId("2E7A4")})
> 
> Mon Aug 17 14:20:56.990 Error: invalid object id: length
> 
> > db.Trips.find({"person.__id" : ObjectId("190372")})
> 
> Mon Aug 17 14:21:10.815 Error: invalid object id: length
> 
> 
> I think they have to be exactly 12.
> 
> 
> Will the implementation of Henrik will come into the next stable version of
> MONGO-BSON package?

yes it will

> 
> 
> Regards
> 
> Sabine
> 
> 
> 
> 
> 2015-08-17 14:04 GMT+02:00 Esteban Lorenzano <notifications@github.com>:
> 
> > I meant inside MongoDB. There it is not an integer… it is a special type.
> > You can create an OID with no matter what number inside (as long as is not
> > bigger than 12b)
> > But I think in the driver it needs to be treated as something different
> > than a number.
> >
> > Esteban
> >
> >

**Comment by estebanlm** [comment]
oops, this is fixed and I forget to close
